/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as PrescriptionsIndexRouteImport } from './routes/prescriptions/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as MedicalRecordsIndexRouteImport } from './routes/medical-records/index'
import { Route as EncountersIndexRouteImport } from './routes/encounters/index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as ServicesManageRouteImport } from './routes/services/manage'
import { Route as ServicesIdRouteImport } from './routes/services/$id'
import { Route as ProductsManageProductsRouteImport } from './routes/products/manage-products'
import { Route as ProductsCreateProductRouteImport } from './routes/products/create-product'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as PrescriptionsNewRouteImport } from './routes/prescriptions/new'
import { Route as PrescriptionsManageRouteImport } from './routes/prescriptions/manage'
import { Route as PrescriptionsIdRouteImport } from './routes/prescriptions/$id'
import { Route as PatientsNewRouteImport } from './routes/patients/new'
import { Route as PatientsIdRouteImport } from './routes/patients/$id'
import { Route as OrdersManageOrdersRouteImport } from './routes/orders/manage-orders'
import { Route as MedicalRecordsNewRouteImport } from './routes/medical-records/new'
import { Route as MedicalRecordsIdRouteImport } from './routes/medical-records/$id'
import { Route as EncountersNewRouteImport } from './routes/encounters/new'
import { Route as EncountersIdRouteImport } from './routes/encounters/$id'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'
import { Route as AppointmentsManageRouteImport } from './routes/appointments/manage'
import { Route as AppointmentsBookRouteImport } from './routes/appointments/book'
import { Route as AppointmentsIdRouteImport } from './routes/appointments/$id'
import { Route as PrescriptionsIdEditRouteImport } from './routes/prescriptions/$id.edit'
import { Route as PatientsIdEditRouteImport } from './routes/patients/$id.edit'
import { Route as MedicalRecordsIdEditRouteImport } from './routes/medical-records/$id.edit'
import { Route as EncountersIdEditRouteImport } from './routes/encounters/$id.edit'
import { Route as AppointmentsIdCancelRouteImport } from './routes/appointments/$id.cancel'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsIndexRoute = PrescriptionsIndexRouteImport.update({
  id: '/prescriptions/',
  path: '/prescriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRecordsIndexRoute = MedicalRecordsIndexRouteImport.update({
  id: '/medical-records/',
  path: '/medical-records/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncountersIndexRoute = EncountersIndexRouteImport.update({
  id: '/encounters/',
  path: '/encounters/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesManageRoute = ServicesManageRouteImport.update({
  id: '/services/manage',
  path: '/services/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsManageProductsRoute = ProductsManageProductsRouteImport.update({
  id: '/products/manage-products',
  path: '/products/manage-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCreateProductRoute = ProductsCreateProductRouteImport.update({
  id: '/products/create-product',
  path: '/products/create-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsNewRoute = PrescriptionsNewRouteImport.update({
  id: '/prescriptions/new',
  path: '/prescriptions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsManageRoute = PrescriptionsManageRouteImport.update({
  id: '/prescriptions/manage',
  path: '/prescriptions/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsIdRoute = PrescriptionsIdRouteImport.update({
  id: '/prescriptions/$id',
  path: '/prescriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersManageOrdersRoute = OrdersManageOrdersRouteImport.update({
  id: '/orders/manage-orders',
  path: '/orders/manage-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRecordsNewRoute = MedicalRecordsNewRouteImport.update({
  id: '/medical-records/new',
  path: '/medical-records/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRecordsIdRoute = MedicalRecordsIdRouteImport.update({
  id: '/medical-records/$id',
  path: '/medical-records/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EncountersNewRoute = EncountersNewRouteImport.update({
  id: '/encounters/new',
  path: '/encounters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EncountersIdRoute = EncountersIdRouteImport.update({
  id: '/encounters/$id',
  path: '/encounters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsManageRoute = AppointmentsManageRouteImport.update({
  id: '/appointments/manage',
  path: '/appointments/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsBookRoute = AppointmentsBookRouteImport.update({
  id: '/appointments/book',
  path: '/appointments/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIdRoute = AppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsIdEditRoute = PrescriptionsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PrescriptionsIdRoute,
} as any)
const PatientsIdEditRoute = PatientsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PatientsIdRoute,
} as any)
const MedicalRecordsIdEditRoute = MedicalRecordsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MedicalRecordsIdRoute,
} as any)
const EncountersIdEditRoute = EncountersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EncountersIdRoute,
} as any)
const AppointmentsIdCancelRoute = AppointmentsIdCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => AppointmentsIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/appointments/$id': typeof AppointmentsIdRouteWithChildren
  '/appointments/book': typeof AppointmentsBookRoute
  '/appointments/manage': typeof AppointmentsManageRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/encounters/$id': typeof EncountersIdRouteWithChildren
  '/encounters/new': typeof EncountersNewRoute
  '/medical-records/$id': typeof MedicalRecordsIdRouteWithChildren
  '/medical-records/new': typeof MedicalRecordsNewRoute
  '/orders/manage-orders': typeof OrdersManageOrdersRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/patients/new': typeof PatientsNewRoute
  '/prescriptions/$id': typeof PrescriptionsIdRouteWithChildren
  '/prescriptions/manage': typeof PrescriptionsManageRoute
  '/prescriptions/new': typeof PrescriptionsNewRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/create-product': typeof ProductsCreateProductRoute
  '/products/manage-products': typeof ProductsManageProductsRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/manage': typeof ServicesManageRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/encounters/': typeof EncountersIndexRoute
  '/medical-records/': typeof MedicalRecordsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/prescriptions/': typeof PrescriptionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/appointments/$id/cancel': typeof AppointmentsIdCancelRoute
  '/encounters/$id/edit': typeof EncountersIdEditRoute
  '/medical-records/$id/edit': typeof MedicalRecordsIdEditRoute
  '/patients/$id/edit': typeof PatientsIdEditRoute
  '/prescriptions/$id/edit': typeof PrescriptionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/appointments/$id': typeof AppointmentsIdRouteWithChildren
  '/appointments/book': typeof AppointmentsBookRoute
  '/appointments/manage': typeof AppointmentsManageRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/encounters/$id': typeof EncountersIdRouteWithChildren
  '/encounters/new': typeof EncountersNewRoute
  '/medical-records/$id': typeof MedicalRecordsIdRouteWithChildren
  '/medical-records/new': typeof MedicalRecordsNewRoute
  '/orders/manage-orders': typeof OrdersManageOrdersRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/patients/new': typeof PatientsNewRoute
  '/prescriptions/$id': typeof PrescriptionsIdRouteWithChildren
  '/prescriptions/manage': typeof PrescriptionsManageRoute
  '/prescriptions/new': typeof PrescriptionsNewRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/create-product': typeof ProductsCreateProductRoute
  '/products/manage-products': typeof ProductsManageProductsRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/manage': typeof ServicesManageRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/encounters': typeof EncountersIndexRoute
  '/medical-records': typeof MedicalRecordsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/prescriptions': typeof PrescriptionsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/appointments/$id/cancel': typeof AppointmentsIdCancelRoute
  '/encounters/$id/edit': typeof EncountersIdEditRoute
  '/medical-records/$id/edit': typeof MedicalRecordsIdEditRoute
  '/patients/$id/edit': typeof PatientsIdEditRoute
  '/prescriptions/$id/edit': typeof PrescriptionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/appointments/$id': typeof AppointmentsIdRouteWithChildren
  '/appointments/book': typeof AppointmentsBookRoute
  '/appointments/manage': typeof AppointmentsManageRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/encounters/$id': typeof EncountersIdRouteWithChildren
  '/encounters/new': typeof EncountersNewRoute
  '/medical-records/$id': typeof MedicalRecordsIdRouteWithChildren
  '/medical-records/new': typeof MedicalRecordsNewRoute
  '/orders/manage-orders': typeof OrdersManageOrdersRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/patients/new': typeof PatientsNewRoute
  '/prescriptions/$id': typeof PrescriptionsIdRouteWithChildren
  '/prescriptions/manage': typeof PrescriptionsManageRoute
  '/prescriptions/new': typeof PrescriptionsNewRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/create-product': typeof ProductsCreateProductRoute
  '/products/manage-products': typeof ProductsManageProductsRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/manage': typeof ServicesManageRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/encounters/': typeof EncountersIndexRoute
  '/medical-records/': typeof MedicalRecordsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/prescriptions/': typeof PrescriptionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/appointments/$id/cancel': typeof AppointmentsIdCancelRoute
  '/encounters/$id/edit': typeof EncountersIdEditRoute
  '/medical-records/$id/edit': typeof MedicalRecordsIdEditRoute
  '/patients/$id/edit': typeof PatientsIdEditRoute
  '/prescriptions/$id/edit': typeof PrescriptionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/appointments/$id'
    | '/appointments/book'
    | '/appointments/manage'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/encounters/$id'
    | '/encounters/new'
    | '/medical-records/$id'
    | '/medical-records/new'
    | '/orders/manage-orders'
    | '/patients/$id'
    | '/patients/new'
    | '/prescriptions/$id'
    | '/prescriptions/manage'
    | '/prescriptions/new'
    | '/products/$id'
    | '/products/create-product'
    | '/products/manage-products'
    | '/services/$id'
    | '/services/manage'
    | '/appointments/'
    | '/encounters/'
    | '/medical-records/'
    | '/orders/'
    | '/patients/'
    | '/prescriptions/'
    | '/products/'
    | '/services/'
    | '/api/auth/$'
    | '/appointments/$id/cancel'
    | '/encounters/$id/edit'
    | '/medical-records/$id/edit'
    | '/patients/$id/edit'
    | '/prescriptions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/appointments/$id'
    | '/appointments/book'
    | '/appointments/manage'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/encounters/$id'
    | '/encounters/new'
    | '/medical-records/$id'
    | '/medical-records/new'
    | '/orders/manage-orders'
    | '/patients/$id'
    | '/patients/new'
    | '/prescriptions/$id'
    | '/prescriptions/manage'
    | '/prescriptions/new'
    | '/products/$id'
    | '/products/create-product'
    | '/products/manage-products'
    | '/services/$id'
    | '/services/manage'
    | '/appointments'
    | '/encounters'
    | '/medical-records'
    | '/orders'
    | '/patients'
    | '/prescriptions'
    | '/products'
    | '/services'
    | '/api/auth/$'
    | '/appointments/$id/cancel'
    | '/encounters/$id/edit'
    | '/medical-records/$id/edit'
    | '/patients/$id/edit'
    | '/prescriptions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/appointments/$id'
    | '/appointments/book'
    | '/appointments/manage'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/encounters/$id'
    | '/encounters/new'
    | '/medical-records/$id'
    | '/medical-records/new'
    | '/orders/manage-orders'
    | '/patients/$id'
    | '/patients/new'
    | '/prescriptions/$id'
    | '/prescriptions/manage'
    | '/prescriptions/new'
    | '/products/$id'
    | '/products/create-product'
    | '/products/manage-products'
    | '/services/$id'
    | '/services/manage'
    | '/appointments/'
    | '/encounters/'
    | '/medical-records/'
    | '/orders/'
    | '/patients/'
    | '/prescriptions/'
    | '/products/'
    | '/services/'
    | '/api/auth/$'
    | '/appointments/$id/cancel'
    | '/encounters/$id/edit'
    | '/medical-records/$id/edit'
    | '/patients/$id/edit'
    | '/prescriptions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AppointmentsIdRoute: typeof AppointmentsIdRouteWithChildren
  AppointmentsBookRoute: typeof AppointmentsBookRoute
  AppointmentsManageRoute: typeof AppointmentsManageRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  EncountersIdRoute: typeof EncountersIdRouteWithChildren
  EncountersNewRoute: typeof EncountersNewRoute
  MedicalRecordsIdRoute: typeof MedicalRecordsIdRouteWithChildren
  MedicalRecordsNewRoute: typeof MedicalRecordsNewRoute
  OrdersManageOrdersRoute: typeof OrdersManageOrdersRoute
  PatientsIdRoute: typeof PatientsIdRouteWithChildren
  PatientsNewRoute: typeof PatientsNewRoute
  PrescriptionsIdRoute: typeof PrescriptionsIdRouteWithChildren
  PrescriptionsManageRoute: typeof PrescriptionsManageRoute
  PrescriptionsNewRoute: typeof PrescriptionsNewRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsCreateProductRoute: typeof ProductsCreateProductRoute
  ProductsManageProductsRoute: typeof ProductsManageProductsRoute
  ServicesIdRoute: typeof ServicesIdRoute
  ServicesManageRoute: typeof ServicesManageRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  EncountersIndexRoute: typeof EncountersIndexRoute
  MedicalRecordsIndexRoute: typeof MedicalRecordsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  PrescriptionsIndexRoute: typeof PrescriptionsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions/': {
      id: '/prescriptions/'
      path: '/prescriptions'
      fullPath: '/prescriptions/'
      preLoaderRoute: typeof PrescriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-records/': {
      id: '/medical-records/'
      path: '/medical-records'
      fullPath: '/medical-records/'
      preLoaderRoute: typeof MedicalRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encounters/': {
      id: '/encounters/'
      path: '/encounters'
      fullPath: '/encounters/'
      preLoaderRoute: typeof EncountersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/manage': {
      id: '/services/manage'
      path: '/services/manage'
      fullPath: '/services/manage'
      preLoaderRoute: typeof ServicesManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/manage-products': {
      id: '/products/manage-products'
      path: '/products/manage-products'
      fullPath: '/products/manage-products'
      preLoaderRoute: typeof ProductsManageProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/create-product': {
      id: '/products/create-product'
      path: '/products/create-product'
      fullPath: '/products/create-product'
      preLoaderRoute: typeof ProductsCreateProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions/new': {
      id: '/prescriptions/new'
      path: '/prescriptions/new'
      fullPath: '/prescriptions/new'
      preLoaderRoute: typeof PrescriptionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions/manage': {
      id: '/prescriptions/manage'
      path: '/prescriptions/manage'
      fullPath: '/prescriptions/manage'
      preLoaderRoute: typeof PrescriptionsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions/$id': {
      id: '/prescriptions/$id'
      path: '/prescriptions/$id'
      fullPath: '/prescriptions/$id'
      preLoaderRoute: typeof PrescriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/manage-orders': {
      id: '/orders/manage-orders'
      path: '/orders/manage-orders'
      fullPath: '/orders/manage-orders'
      preLoaderRoute: typeof OrdersManageOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-records/new': {
      id: '/medical-records/new'
      path: '/medical-records/new'
      fullPath: '/medical-records/new'
      preLoaderRoute: typeof MedicalRecordsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-records/$id': {
      id: '/medical-records/$id'
      path: '/medical-records/$id'
      fullPath: '/medical-records/$id'
      preLoaderRoute: typeof MedicalRecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encounters/new': {
      id: '/encounters/new'
      path: '/encounters/new'
      fullPath: '/encounters/new'
      preLoaderRoute: typeof EncountersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encounters/$id': {
      id: '/encounters/$id'
      path: '/encounters/$id'
      fullPath: '/encounters/$id'
      preLoaderRoute: typeof EncountersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/manage': {
      id: '/appointments/manage'
      path: '/appointments/manage'
      fullPath: '/appointments/manage'
      preLoaderRoute: typeof AppointmentsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/book': {
      id: '/appointments/book'
      path: '/appointments/book'
      fullPath: '/appointments/book'
      preLoaderRoute: typeof AppointmentsBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$id': {
      id: '/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions/$id/edit': {
      id: '/prescriptions/$id/edit'
      path: '/edit'
      fullPath: '/prescriptions/$id/edit'
      preLoaderRoute: typeof PrescriptionsIdEditRouteImport
      parentRoute: typeof PrescriptionsIdRoute
    }
    '/patients/$id/edit': {
      id: '/patients/$id/edit'
      path: '/edit'
      fullPath: '/patients/$id/edit'
      preLoaderRoute: typeof PatientsIdEditRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/medical-records/$id/edit': {
      id: '/medical-records/$id/edit'
      path: '/edit'
      fullPath: '/medical-records/$id/edit'
      preLoaderRoute: typeof MedicalRecordsIdEditRouteImport
      parentRoute: typeof MedicalRecordsIdRoute
    }
    '/encounters/$id/edit': {
      id: '/encounters/$id/edit'
      path: '/edit'
      fullPath: '/encounters/$id/edit'
      preLoaderRoute: typeof EncountersIdEditRouteImport
      parentRoute: typeof EncountersIdRoute
    }
    '/appointments/$id/cancel': {
      id: '/appointments/$id/cancel'
      path: '/cancel'
      fullPath: '/appointments/$id/cancel'
      preLoaderRoute: typeof AppointmentsIdCancelRouteImport
      parentRoute: typeof AppointmentsIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppointmentsIdRouteChildren {
  AppointmentsIdCancelRoute: typeof AppointmentsIdCancelRoute
}

const AppointmentsIdRouteChildren: AppointmentsIdRouteChildren = {
  AppointmentsIdCancelRoute: AppointmentsIdCancelRoute,
}

const AppointmentsIdRouteWithChildren = AppointmentsIdRoute._addFileChildren(
  AppointmentsIdRouteChildren,
)

interface EncountersIdRouteChildren {
  EncountersIdEditRoute: typeof EncountersIdEditRoute
}

const EncountersIdRouteChildren: EncountersIdRouteChildren = {
  EncountersIdEditRoute: EncountersIdEditRoute,
}

const EncountersIdRouteWithChildren = EncountersIdRoute._addFileChildren(
  EncountersIdRouteChildren,
)

interface MedicalRecordsIdRouteChildren {
  MedicalRecordsIdEditRoute: typeof MedicalRecordsIdEditRoute
}

const MedicalRecordsIdRouteChildren: MedicalRecordsIdRouteChildren = {
  MedicalRecordsIdEditRoute: MedicalRecordsIdEditRoute,
}

const MedicalRecordsIdRouteWithChildren =
  MedicalRecordsIdRoute._addFileChildren(MedicalRecordsIdRouteChildren)

interface PatientsIdRouteChildren {
  PatientsIdEditRoute: typeof PatientsIdEditRoute
}

const PatientsIdRouteChildren: PatientsIdRouteChildren = {
  PatientsIdEditRoute: PatientsIdEditRoute,
}

const PatientsIdRouteWithChildren = PatientsIdRoute._addFileChildren(
  PatientsIdRouteChildren,
)

interface PrescriptionsIdRouteChildren {
  PrescriptionsIdEditRoute: typeof PrescriptionsIdEditRoute
}

const PrescriptionsIdRouteChildren: PrescriptionsIdRouteChildren = {
  PrescriptionsIdEditRoute: PrescriptionsIdEditRoute,
}

const PrescriptionsIdRouteWithChildren = PrescriptionsIdRoute._addFileChildren(
  PrescriptionsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AppointmentsIdRoute: AppointmentsIdRouteWithChildren,
  AppointmentsBookRoute: AppointmentsBookRoute,
  AppointmentsManageRoute: AppointmentsManageRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  EncountersIdRoute: EncountersIdRouteWithChildren,
  EncountersNewRoute: EncountersNewRoute,
  MedicalRecordsIdRoute: MedicalRecordsIdRouteWithChildren,
  MedicalRecordsNewRoute: MedicalRecordsNewRoute,
  OrdersManageOrdersRoute: OrdersManageOrdersRoute,
  PatientsIdRoute: PatientsIdRouteWithChildren,
  PatientsNewRoute: PatientsNewRoute,
  PrescriptionsIdRoute: PrescriptionsIdRouteWithChildren,
  PrescriptionsManageRoute: PrescriptionsManageRoute,
  PrescriptionsNewRoute: PrescriptionsNewRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsCreateProductRoute: ProductsCreateProductRoute,
  ProductsManageProductsRoute: ProductsManageProductsRoute,
  ServicesIdRoute: ServicesIdRoute,
  ServicesManageRoute: ServicesManageRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  EncountersIndexRoute: EncountersIndexRoute,
  MedicalRecordsIndexRoute: MedicalRecordsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  PrescriptionsIndexRoute: PrescriptionsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
